---
- name: unzip nginx package for remote hosts
  unarchive: src=nginx-1.14.0.tar.gz desc={{ download_dir }}
  name: install nginx
  shell: cd {{ download_dir }}/nginx-1.14.0/ && ./configure --prefix={{ app_dir }}/nginx  --user=www --group=www --with-http_ssl_module --with-http_flv_module --with-http_stub_status_module --with-http_gzip_static_module   && make && make install

- name: copy nginx.conf to remote hosts
  template: src=nginx.conf desc={{ app_dir }}/nginx/conf/nginx.conf
  notify:
    - restart nginx service

- name: copy nginx boot script to /etc/init.d
  copy: src=./files/nginx desc=/etc/init.d

- name: boot nginx
  service: name=nginx state=started
