#!/bin/bash

#nginx management nginx
#chkconfig:- 85 15
#config /usr/local/nginx/conf/nginx.conf
#source function library

. /etc/rc.d/init.d/functions

if [ -L $0 ];then
    initscript=`/bin/readlink -f $0`
else
    initscript=$0
fi


sysconfig=`/bin/basename $initscript`


if [ -f /etc/sysconfig/$sysconfig ];then
    . /etc/sysconfig/$sysconfig
fi

nginx=${NGINX:-/usr/local/nginx/sbin/nginx}
prog=`/bin/basename $nginx`
configfile=${CONFIGFILE:-/usr/local/nginx/conf/nginx.conf}
lockfile=${LOCKFILE:-/var/lock/subsys/nginx}
